import { readFile, writeFile } from 'node:fs/promises';

const values = JSON.parse(await readFile(new URL('../src/tokens/values.json', import.meta.url), 'utf8'));
const lines = Object.entries(values).map(([name, value]) => `  --forge-${name}: ${value};`);
const fallback = {
  'surface-shell': '#e7edf7', 'surface-panel': '#f7faff', 'surface-rail': '#edf4fd',
  'surface-elevated': '#f8fbff', 'surface-floating': '#fafcff',
  'blur-shell': '0px', 'blur-glass': '0px', 'blur-overlay': '0px',
};
const fallbackLines = Object.entries(fallback).map(([name, value]) => `  --forge-${name}: ${value};`);
const css = `/* Generated by packages/ui/scripts/build-tokens.mjs from values.json. */\n:root {\n  color-scheme: light;\n${lines.join('\n')}\n}\n\n[data-reduce-transparency='true'] {\n${fallbackLines.join('\n')}\n}\n\n@media (prefers-reduced-transparency: reduce) {\n  :root {\n${fallbackLines.map((line) => `  ${line}`).join('\n')}\n  }\n}\n\n[data-reduce-motion='true'] {\n  --forge-motion-fast: 0ms;\n  --forge-motion-normal: 0ms;\n  --forge-motion-slow: 0ms;\n  --forge-motion-page: 0ms;\n  --forge-motion-hover: 0ms;\n}\n\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --forge-motion-fast: 0ms;\n    --forge-motion-normal: 0ms;\n    --forge-motion-slow: 0ms;\n    --forge-motion-page: 0ms;\n    --forge-motion-hover: 0ms;\n  }\n}\n`;
const target = new URL('../src/tokens.css', import.meta.url);
if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8');
  if (current !== css) throw new Error('tokens.css is out of sync with values.json');
} else {
  await writeFile(target, css);
}
