/** @vitest-environment jsdom */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { InsightsSession, InsightsStreamChunk, InsightsChatStatus, InsightsRequestIdentity, InsightsGenerationResult, InsightsCancellationResult, InsightsIPCResult, InsightsErrorCode } from '../../../shared/types';
import { loadInsightsSession, loadInsightsSessions, newSession, sendMessage, regenerateMessage, cancelMessage, setupInsightsListeners, switchSession, useInsightsStore } from '../insights-store';

function deferred<T>() { let resolve!: (value:T)=>void; const promise=new Promise<T>(done=>{resolve=done;}); return {promise,resolve}; }
const session=(projectId:string,id=`${projectId}-session`):InsightsSession=>({id,projectId,messages:[],createdAt:new Date(),updatedAt:new Date()});
const user={id:'user',role:'user' as const,content:'Explain A',timestamp:new Date()};
const answer={id:'answer',role:'assistant' as const,content:'Original answer',timestamp:new Date()};
let stream:(project:string,chunk:InsightsStreamChunk)=>void;
let status:(project:string,status:InsightsChatStatus)=>void;
let error:(project:string,error:string,sessionId?:string,requestId?:string,code?:InsightsErrorCode)=>void;
let updated:(project:string,session:InsightsSession,requestId?:string)=>void;
const unsubs=[vi.fn(),vi.fn(),vi.fn(),vi.fn()];
const api={getInsightsSession:vi.fn(),listInsightsSessions:vi.fn(),getInsightsActiveRequest:vi.fn(),newInsightsSession:vi.fn(),switchInsightsSession:vi.fn(),sendInsightsMessage:vi.fn(),regenerateInsightsMessage:vi.fn(),cancelInsightsMessage:vi.fn(),onInsightsStreamChunk:vi.fn(),onInsightsStatus:vi.fn(),onInsightsError:vi.fn(),onInsightsSessionUpdated:vi.fn()};
let previous:typeof window.electronAPI;let cleanups:Array<()=>void>=[];
function listen(project:string,messages:InsightsSession['messages']=[]){cleanups.push(setupInsightsListeners(project));useInsightsStore.getState().setSession({...session(project),messages});}
function active():InsightsRequestIdentity{const req=useInsightsStore.getState().activeRequest;if(!req)throw new Error('Expected active request');return {sessionId:req.sessionId,requestId:req.requestId};}
const complete=(request:InsightsRequestIdentity,outcome:'complete'|'cancelled'='complete')=>({success:true,data:{...request,outcome}});
const flush=()=>new Promise(done=>setTimeout(done,0));
beforeEach(()=>{previous=window.electronAPI;Object.defineProperty(window,'electronAPI',{configurable:true,value:api});Object.values(api).forEach(mock=>mock.mockReset());unsubs.forEach(mock=>mock.mockClear());api.onInsightsStreamChunk.mockImplementation(cb=>{stream=cb;return unsubs[0];});api.onInsightsStatus.mockImplementation(cb=>{status=cb;return unsubs[1];});api.onInsightsError.mockImplementation(cb=>{error=cb;return unsubs[2];});api.onInsightsSessionUpdated.mockImplementation(cb=>{updated=cb;return unsubs[3];});api.listInsightsSessions.mockResolvedValue({success:true,data:[]});api.getInsightsActiveRequest.mockResolvedValue({success:true,data:null});api.getInsightsSession.mockImplementation(async(project:string)=>({success:true,data:session(project)}));api.sendInsightsMessage.mockImplementation(()=>new Promise(()=>{/* Intentionally pending generation. */}));api.regenerateInsightsMessage.mockImplementation(()=>new Promise(()=>{/* Intentionally pending generation. */}));useInsightsStore.getState().clearSession();useInsightsStore.setState({sessions:[],isLoadingSessions:false});});
afterEach(()=>{cleanups.forEach(cleanup=>cleanup());cleanups=[];useInsightsStore.getState().clearSession();Object.defineProperty(window,'electronAPI',{configurable:true,value:previous});});

describe('Insights correlated generation lifecycle',()=>{
 it('uses persisted assistant identity and does not duplicate a completed streamed reply',async()=>{listen('A');const pending=deferred<InsightsIPCResult<InsightsGenerationResult>>();api.sendInsightsMessage.mockReturnValue(pending.promise);const sending=sendMessage('A','Explain A');const request=active();stream('A',{type:'text',content:'Current response',...request});expect(useInsightsStore.getState().streamingContent).toBe('Current response');const persisted={...session('A'),messages:[user,answer]};updated('A',persisted,request.requestId);stream('A',{type:'done',...request});expect(useInsightsStore.getState().activeRequest).not.toBeNull();expect(useInsightsStore.getState().session?.messages).toHaveLength(2);api.getInsightsSession.mockResolvedValue({success:true,data:persisted});pending.resolve(complete(request));expect(await sending).toBe(true);expect(useInsightsStore.getState().session?.messages.map(m=>m.id)).toEqual(['user','answer']);expect(useInsightsStore.getState().activeRequest).toBeNull();expect(api.sendInsightsMessage).toHaveBeenCalledWith('A','Explain A',undefined,undefined,request);});
 it('waits for Stop acknowledgment when send settles first and suppresses late cancelled chunks',async()=>{listen('A');const sendingResult=deferred<InsightsIPCResult<InsightsGenerationResult>>();const cancelled=deferred<InsightsIPCResult<InsightsCancellationResult>>();api.sendInsightsMessage.mockReturnValue(sendingResult.promise);api.cancelInsightsMessage.mockReturnValue(cancelled.promise);const sending=sendMessage('A','Explain A');const request=active();const stopping=cancelMessage('A');stream('A',{type:'text',content:'Late partial',...request});sendingResult.resolve(complete(request,'cancelled'));await sending;expect(useInsightsStore.getState().activeRequest?.phase).toBe('stopping');expect(await sendMessage('A','Premature next')).toBe(false);expect(useInsightsStore.getState().streamingContent).toBe('');api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A'),messages:[user]}});cancelled.resolve({success:true,data:{...request,cancelled:true}});expect(await stopping).toBe(true);expect(useInsightsStore.getState().activeRequest).toBeNull();stream('A',{type:'text',content:'After stop',...request});expect(useInsightsStore.getState().streamingContent).toBe('');expect(useInsightsStore.getState().session?.messages).toEqual([user]);});
 it('does not label a naturally completed response as stopped',async()=>{listen('A');void sendMessage('A','Explain A');const request=active();api.cancelInsightsMessage.mockResolvedValue({success:true,data:{...request,cancelled:false}});await cancelMessage('A');expect(useInsightsStore.getState().status.message).toBe('');});
 it('keeps Stop available when cancellation fails and rejects overlapping sends',async()=>{listen('A');void sendMessage('A','Explain A');const request=active();api.cancelInsightsMessage.mockRejectedValue(new Error('secret transport details'));expect(await cancelMessage('A')).toBe(false);expect(useInsightsStore.getState().activeRequest?.requestId).toBe(request.requestId);expect(await sendMessage('A','Overlap')).toBe(false);expect(useInsightsStore.getState().status.error).not.toContain('secret');});
 it('retains the original reply on failed regenerate and discards replacement partial text',async()=>{listen('A',[user,answer]);const pending=deferred<InsightsIPCResult<InsightsGenerationResult>>();api.regenerateInsightsMessage.mockReturnValue(pending.promise);const regenerating=regenerateMessage('A',answer.id);const request=active();stream('A',{type:'text',content:'Failed replacement',...request});expect(useInsightsStore.getState().session?.messages).toEqual([user,answer]);api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A'),messages:[user,answer]}});pending.resolve({success:false,error:'raw SDK secret',code:'request-failed'});expect(await regenerating).toBe(false);expect(useInsightsStore.getState().session?.messages).toEqual([user,answer]);expect(useInsightsStore.getState().streamingContent).toBe('');expect(useInsightsStore.getState().status.error).not.toContain('secret');expect(api.regenerateInsightsMessage).toHaveBeenCalledWith('A',{...request,targetMessageId:answer.id,images:undefined},undefined);expect(api.sendInsightsMessage).not.toHaveBeenCalled();});
 it('replaces a successful regenerated reply instead of appending it',async()=>{listen('A',[user,answer]);const pending=deferred<InsightsIPCResult<InsightsGenerationResult>>();api.regenerateInsightsMessage.mockReturnValue(pending.promise);const running=regenerateMessage('A',answer.id);const request=active();api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A'),messages:[user,{...answer,id:'new-answer'}]}});pending.resolve(complete(request));expect(await running).toBe(true);expect(useInsightsStore.getState().session?.messages.map(m=>m.id)).toEqual(['user','new-answer']);});
 it('retries an unanswered persisted user with reattached images without duplicating the prompt',()=>{listen('A',[user]);const images=[{id:'image',filename:'a.png',mimeType:'image/png',size:1,data:'AAAA'}];void sendMessage('A',user.content,undefined,images);const request=active();expect(api.regenerateInsightsMessage).toHaveBeenCalledWith('A',{...request,targetMessageId:user.id,images},undefined);expect(api.sendInsightsMessage).not.toHaveBeenCalled();expect(useInsightsStore.getState().session?.messages).toEqual([user]);});
 it('rejects late old request text, status, error and session updates within the same session',async()=>{listen('A');const pending=deferred<InsightsIPCResult<InsightsGenerationResult>>();api.sendInsightsMessage.mockReturnValueOnce(pending.promise);const sending=sendMessage('A','Explain A');const old=active();api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A'),messages:[user]}});pending.resolve({success:false,code:'request-failed'});await sending;void regenerateMessage('A',user.id);const current=active();stream('A',{type:'text',content:'Old text',...old});status('A',{phase:'error',error:'Old status',...old});error('A','Old error',old.sessionId,old.requestId);updated('A',{...session('A'),messages:[user,answer]},old.requestId);expect(useInsightsStore.getState().streamingContent).toBe('');expect(useInsightsStore.getState().status.phase).toBe('thinking');expect(useInsightsStore.getState().session?.messages).toEqual([user]);stream('A',{type:'text',content:'New text',...current});expect(useInsightsStore.getState().streamingContent).toBe('New text');});
 it('restores a remote active request on session return and completes from persisted events',async()=>{listen('A');const request={sessionId:'A-session',requestId:'remote',phase:'streaming' as const};api.getInsightsActiveRequest.mockResolvedValueOnce({success:true,data:request});await loadInsightsSession('A');expect(useInsightsStore.getState().activeRequest).toEqual(request);stream('A',{type:'text',content:'Resumed text',...request});expect(useInsightsStore.getState().streamingContent).toBe('Resumed text');api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A'),messages:[user,answer]}});stream('A',{type:'done',...request});await flush();expect(useInsightsStore.getState().activeRequest).toBeNull();expect(useInsightsStore.getState().session?.messages).toEqual([user,answer]);});
 it('releases a rehydrated stopping request only after Main confirms it ended',async()=>{listen('A');const request={sessionId:'A-session',requestId:'remote-stop',phase:'stopping' as const};api.getInsightsActiveRequest.mockResolvedValueOnce({success:true,data:request});await loadInsightsSession('A');expect(useInsightsStore.getState().activeRequest?.phase).toBe('stopping');stream('A',{type:'text',content:'Cancelled late partial',...request});expect(useInsightsStore.getState().streamingContent).toBe('');status('A',{...request,phase:'idle'});await flush();expect(useInsightsStore.getState().activeRequest).toBeNull();expect(useInsightsStore.getState().status.phase).toBe('complete');});
 it('finishes a returned session after its send Promise from the old view settles',async()=>{listen('A');const pending=deferred<InsightsIPCResult<InsightsGenerationResult>>();api.sendInsightsMessage.mockReturnValue(pending.promise);const sending=sendMessage('A','Explain A');const request=active();listen('B');listen('A');api.getInsightsActiveRequest.mockResolvedValueOnce({success:true,data:{...request,phase:'streaming'}});await loadInsightsSession('A');api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A'),messages:[user,answer]}});stream('A',{type:'done',...request});expect(useInsightsStore.getState().activeRequest).not.toBeNull();pending.resolve(complete(request));await sending;await flush();expect(useInsightsStore.getState().activeRequest).toBeNull();expect(useInsightsStore.getState().session?.messages).toEqual([user,answer]);});
 it('finishes a returned stopping session after the old Stop acknowledgment settles',async()=>{listen('A');const sendResult=deferred<InsightsIPCResult<InsightsGenerationResult>>();const stopResult=deferred<InsightsIPCResult<InsightsCancellationResult>>();api.sendInsightsMessage.mockReturnValue(sendResult.promise);api.cancelInsightsMessage.mockReturnValue(stopResult.promise);const sending=sendMessage('A','Explain A');const request=active();const stopping=cancelMessage('A');listen('B');listen('A');api.getInsightsActiveRequest.mockResolvedValueOnce({success:true,data:{...request,phase:'stopping'}});await loadInsightsSession('A');api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A'),messages:[user]}});status('A',{...request,phase:'idle'});sendResult.resolve(complete(request,'cancelled'));await sending;expect(useInsightsStore.getState().activeRequest?.phase).toBe('stopping');stopResult.resolve({success:true,data:{...request,cancelled:true}});await stopping;await flush();expect(useInsightsStore.getState().activeRequest).toBeNull();expect(useInsightsStore.getState().session?.messages).toEqual([user]);});
 it('rejects identity-free and other-project/session events',()=>{listen('A');void sendMessage('A','Explain A');const request=active();stream('A',{type:'text',content:'No identity'});stream('B',{type:'text',content:'Other project',...request});stream('A',{type:'text',content:'Other session',...request,sessionId:'another'});error('A','Unknown error');expect(useInsightsStore.getState().streamingContent).toBe('');expect(useInsightsStore.getState().status.phase).toBe('thinking');});
});

describe('Insights visible project/session loading scope',()=>{
 it('ignores a delayed old-project load after navigating',async()=>{const old=deferred<{success:boolean;data:InsightsSession}>();api.getInsightsSession.mockReturnValueOnce(old.promise).mockResolvedValueOnce({success:true,data:session('B')});listen('A');const loading=loadInsightsSession('A');listen('B');await loadInsightsSession('B');old.resolve({success:true,data:session('A')});await loading;expect(useInsightsStore.getState().session?.projectId).toBe('B');expect(api.listInsightsSessions).toHaveBeenCalledTimes(1);});
 it('keeps the newer same-project session selection',async()=>{listen('A');const old=deferred<{success:boolean;data:InsightsSession}>();api.switchInsightsSession.mockReturnValueOnce(old.promise).mockResolvedValueOnce({success:true,data:session('A','new')});const loading=switchSession('A','old');await switchSession('A','new');old.resolve({success:true,data:session('A','old')});await loading;expect(useInsightsStore.getState().session?.id).toBe('new');});
 it('drops previous-session streams after switching without implicitly cancelling',async()=>{listen('A');void sendMessage('A','Explain A');const old=active();api.switchInsightsSession.mockResolvedValue({success:true,data:session('A','next')});await switchSession('A','next');stream('A',{type:'text',content:'Previous answer',...old});expect(useInsightsStore.getState().streamingContent).toBe('');expect(useInsightsStore.getState().activeRequest).toBeNull();expect(api.cancelInsightsMessage).not.toHaveBeenCalled();});
 it('blocks sends while loading and rejects cross-project persisted data',async()=>{listen('B');const result=deferred<{success:boolean;data:InsightsSession}>();api.getInsightsSession.mockReturnValueOnce(result.promise);const loading=loadInsightsSession('B');expect(await sendMessage('B','Too early')).toBe(false);result.resolve({success:true,data:session('A')});await loading;expect(useInsightsStore.getState().session).toBeNull();expect(api.sendInsightsMessage).not.toHaveBeenCalled();});
 it('keeps only the latest session list',async()=>{listen('A');const old=deferred<{success:boolean;data:[]}>();api.listInsightsSessions.mockReturnValueOnce(old.promise).mockResolvedValueOnce({success:true,data:[{...session('A','latest'),title:'Latest',messageCount:0}]});const loading=loadInsightsSessions('A');await loadInsightsSessions('A',true);old.resolve({success:true,data:[]});await loading;expect(useInsightsStore.getState().sessions[0].id).toBe('latest');});
 it('creates a persisted session before the first send',async()=>{cleanups.push(setupInsightsListeners('A'));api.newInsightsSession.mockResolvedValue({success:true,data:session('A','created')});const pending=deferred<InsightsIPCResult<InsightsGenerationResult>>();api.sendInsightsMessage.mockReturnValue(pending.promise);const sending=sendMessage('A','Explain A');await flush();const request=active();expect(request.sessionId).toBe('created');api.getInsightsSession.mockResolvedValue({success:true,data:{...session('A','created'),messages:[user,answer]}});pending.resolve(complete(request));await sending;expect(api.sendInsightsMessage).toHaveBeenCalledWith('A','Explain A',undefined,undefined,request);});
 it('sanitizes first-session creation failures and never sends without a persisted identity',async()=>{cleanups.push(setupInsightsListeners('A'));api.newInsightsSession.mockRejectedValue(new Error('secret local path'));expect(await sendMessage('A','Keep my input')).toBe(false);expect(api.sendInsightsMessage).not.toHaveBeenCalled();expect(useInsightsStore.getState().session).toBeNull();expect(useInsightsStore.getState().status.code).toBe('persistence-failed');expect(useInsightsStore.getState().status.error).not.toContain('secret');});
 it('invalidates delayed loads and unsubscribes on cleanup',async()=>{const pending=deferred<{success:boolean;data:InsightsSession}>();api.getInsightsSession.mockReturnValue(pending.promise);const cleanup=setupInsightsListeners('A');cleanups.push(cleanup);const loading=loadInsightsSession('A');cleanup();pending.resolve({success:true,data:session('A')});await loading;expect(useInsightsStore.getState().session).toBeNull();unsubs.forEach(unsubscribe=>expect(unsubscribe).toHaveBeenCalledTimes(1));});
 it('does not attach delayed new sessions after changing projects',async()=>{cleanups.push(setupInsightsListeners('A'));const pending=deferred<{success:boolean;data:InsightsSession}>();api.newInsightsSession.mockReturnValue(pending.promise);const creating=newSession('A');listen('B');pending.resolve({success:true,data:session('A')});await creating;expect(useInsightsStore.getState().session?.projectId).toBe('B');});
});
